//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnerCable.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CorreccionMovimientos
    {
        public int IdCorreccionMovimiento { get; set; }
        public int IdTabla { get; set; }
        public int MOV_CONSPOL { get; set; }
        public int MOV_CONSMOV { get; set; }
        public int MOV_MES { get; set; }
        public string MOV_TIPOPOL { get; set; }
        public bool AplicaFactura { get; set; }
        public string Factura { get; set; }
        public bool AplicaSerie { get; set; }
        public string Serie { get; set; }
        public System.DateTime FechaSistema { get; set; }
        public long IdSesion { get; set; }
    }
}
