//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnerCable.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovimientosVentas
    {
        public int IdMovimientoVenta { get; set; }
        public int IdUsuario { get; set; }
        public string Factura { get; set; }
        public string Serie { get; set; }
        public string Mov_TipoPol { get; set; }
        public string MOV_CONSPOL { get; set; }
        public decimal MOV_CONSMOV { get; set; }
        public decimal MOV_MES { get; set; }
        public string MOV_NUMCTA { get; set; }
        public string MOV_CONCEPTO { get; set; }
        public Nullable<decimal> MOV_DEBE { get; set; }
        public Nullable<decimal> MOV_HABER { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string Cate { get; set; }
        public string MOV_FECHOPE { get; set; }
        public string MOV_HORAOPE { get; set; }
        public System.DateTime FechaSistema { get; set; }
        public long IdSesion { get; set; }
    }
}
