//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnerCable.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TiposDePolizas
    {
        public int IdTipoDePoliza { get; set; }
        public string TipoDePoliza { get; set; }
        public string AplicaNombreCuenta { get; set; }
        public string AplicaCondicionNombreCuenta { get; set; }
        public int Posicion { get; set; }
        public int Longitud { get; set; }
        public string TipoExtraccion { get; set; }
        public string DatoValidar { get; set; }
        public string Cate { get; set; }
        public string AplicaFacturaEnSerie { get; set; }
        public System.DateTime FechaSistema { get; set; }
        public long IdSesion { get; set; }
    }
}
