//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnerCable.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwCuentasCostos
    {
        public int IdCuentaCosto { get; set; }
        public string Cuenta { get; set; }
        public string Nombre { get; set; }
        public int IdTipoCuenta { get; set; }
        public System.DateTime FechaSistema { get; set; }
        public long IdSesion { get; set; }
        public string TipoCuenta { get; set; }
    }
}
